# Generated by Django 4.2.20 on 2025-04-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
    ]
