version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: attendance_db     # Database name
      POSTGRES_USER: django_user      # Database user
      POSTGRES_PASSWORD: secretpass   # Strong password (change this!)
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Persists data
    ports:
      - "5432:5432"  # Exposes PostgreSQL port (optional)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d attendance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Django Application Service
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # PostgreSQL connection (comment out to use SQLite)
      - DATABASE_URL=postgres://django_user:secretpass@db:5432/attendance_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:  # Named volume for PostgreSQL persistence