# Generated by Django 4.2.20 on 2025-04-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='group.group')),
            ],
        ),
    ]
