# Generated by Django 4.2.20 on 2025-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='para',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
