# Generated by Django 4.2.20 on 2025-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lesson_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
