# Generated by Django 4.2.20 on 2025-04-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='-', max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lesson.lesson')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student')),
            ],
        ),
    ]
